### ISSUE TITLE
Cannot read property 'getNode' of null

### ISSUE THREAD

**Issue by samithbharadwaj** [mohebifar/react-native-easy-dnd#5]

**Comment by samithbharadwaj** [comment]
I managed to add react-native easy-dnd to my crna app (without expo) and the drag and drop works perfectly. Just as intended. 

However, when I try to navigate to another screen, I'm unable to do that, due to the following error. 

![Screenshot 2019-11-09 at 6 13 27 PM](https://user-images.githubusercontent.com/16634631/68528791-687a4580-031d-11ea-8aa5-26d14d7927b8.png)

What do I change in order to get it to work?
@mohebifar

**Comment by littletower** [comment]
I believe this issue is fixed in 1.0.2, but it has not been published on npm yet #4

**Comment by mohebifar** [comment]
Sorry, CI appears to be have been broken. I just did publish 1.0.2.
